version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
      timezone: "Europe/Warsaw"
    open-pull-requests-limit: 5

    groups:
      dependencies:
        patterns:
          - "*"