name: Main App CI

permissions:
  contents: read
  packages: read
  id-token: write

on:
   push:
     branches:
       - main
     paths-ignore:
       - 'docs/**'
       - '**/*.md'
       - '.github/**'
   workflow_dispatch:
     inputs:
       working-directory:
         type: string
         description: working directory

jobs:
  software-composition-analysis:
    uses: ./.github/workflows/_sca.yaml
    with:
      working-directory: "./spark-model"

  maven-build-test:
    needs:
      - software-composition-analysis
    uses: ./.github/workflows/_maven-build-test.yaml
    with:
      working-directory: "./spark-model"
      java-version: '21'